// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjw4zJtAD9_sIP1vIi6gug4OXc-sxLUaM',
    appId: '1:303143911893:web:2ae9ff2a110298ee147d5c',
    messagingSenderId: '303143911893',
    projectId: 'hepmap-a20a3',
    authDomain: 'hepmap-a20a3.firebaseapp.com',
    storageBucket: 'hepmap-a20a3.appspot.com',
    measurementId: 'G-3RK2N63D9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1yQNW2diI3OruYCyLcWRhd3WQ7SLmWkc',
    appId: '1:303143911893:android:94d3a17d57b4c3f1147d5c',
    messagingSenderId: '303143911893',
    projectId: 'hepmap-a20a3',
    storageBucket: 'hepmap-a20a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZuzM262fq_idI1ZzXltU1Lu1nrzooI34',
    appId: '1:303143911893:ios:4684551baf22db02147d5c',
    messagingSenderId: '303143911893',
    projectId: 'hepmap-a20a3',
    storageBucket: 'hepmap-a20a3.appspot.com',
    iosClientId: '303143911893-sull6b92smk70b55p29617lhlnbevj19.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackWithIo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZuzM262fq_idI1ZzXltU1Lu1nrzooI34',
    appId: '1:303143911893:ios:4684551baf22db02147d5c',
    messagingSenderId: '303143911893',
    projectId: 'hepmap-a20a3',
    storageBucket: 'hepmap-a20a3.appspot.com',
    iosClientId: '303143911893-sull6b92smk70b55p29617lhlnbevj19.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackWithIo',
  );
}
